#include "fxaa_shared.h"
#include "math/color.hlsl"

ConstantBuffer<FXAAConstants> g_Constants;
Texture2D<float4> g_Input;
RWTexture2D<float4> g_Output;

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void main(uint2 gtid : SV_GroupThreadID, uint2 gid : SV_GroupID, uint2 did : SV_DispatchThreadID)
{
    uint2 pixelCoordinates = did;
    if (any(pixelCoordinates >= g_Constants.screenSize.xy))
    {
        return;
    }

    g_Output[pixelCoordinates] = g_Input.Load(int3(pixelCoordinates, 0));
}
